### ISSUE TITLE
Autoreload für selectfelder

### ISSUE THREAD

**Issue by Kahmoon** [MetaModels/attribute_translatedselect#10]
Hi,

das Feld "Auswahl" bräuchte bitte auch noch die Option eines Reloads/autosubmit bei Auswahl bzw. Änderung. Das gibt es das wohl momentan nur bei Checkboxen.

Aktuelles Beispiel ist eine Anpassung der Eingabemaske die abhängig von Kategorien ist. Sprich Redakteur legt einen Eintrag an und je nach Kategorie werden mehr oder weniger Eingabefelder eingeblendet.

Aktuell wird die Seite nicht refreshed wenn die Auswahl geändert wird. Sprich er sieht trotz Auswahl vielleicht die falschen oder zu wenig Felder.

Beitrag im Forum: https://community.contao.org/de/showthread.php?52466-Herangehensweise-f%FCr-Stadtportal-bei-MM&p=338525#post338525

VG
Frank

**Comment by xantippe** [comment]
![shot107](https://cloud.githubusercontent.com/assets/1045318/13157584/f6de985a-d688-11e5-8f9f-a39382e8f0f5.jpg)
