### ISSUE TITLE
Wert aus TranslatedSelect wird in der falschen Sprache ausgegeben

### ISSUE THREAD

**Issue by Teetrinker** [MetaModels/attribute_translatedselect#11]
Mehrsprachiges Metamodel mit einem Attribut TranslatedSelect. In der Ausgabe wird der Wert des Attributes in der falschen Sprache ausgegeben (wahrscheinlich in der Fallback-Sprache).

Beispiel:
Ein Metamodel "Unterkategorie" mit einem Attribut "Kategorie" (anderes Metamodel). Beide dreisprachig (D/e/f).

Im Template der französischen Detailseite des MM dumpe ich die übergebenen Variablen (Auszug):

    [0] => Array
        (
            [raw] => Array
                (
                    [category] => Array
                        (
                            [langcode] => de
                            [value] => Innenarchitektur
                            [mm_subcategory_id] => 5
                        )

                    [name] => Array
                        (
                            [langcode] => fr
                            [value] => Design [Architecture intérieure]
                        )

                    [alias] => Array
                        (
                            [langcode] => fr
                            [value] => design-innenarchitektur
                        )

                    [text] => Array
                        (
                            [langcode] => fr
                            [value] => ...
                        )

Alle Variablen werden in der korrekten Sprache ausgegeben. Nur die TranslatedSelect-Ausgabe erscheint in der falschen Sprache.

Verwendet wurde Mm-nightly-build vom 23.08.2014

**Comment by xantippe** [comment]
@Teetrinker bitte prüfen, ob noch aktuell

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Teetrinker could you please have a final look at this and tell if your issue has been resolved?

**Comment by Teetrinker** [comment]
Habe derzeit leider nicht die Zeit um das zu testen.
