### ISSUE TITLE
Empty option

### ISSUE THREAD

**Issue by EDsolution** [MetaModels/attribute_translatedselect#12]
I have two MM. 
1. = is real estate list
2. = property type (house, apartment, etc.)

The 2. MM is just one input with items (house, apartment, etc.).
The 1. MM has estate data (price, info, size, and property type). Now the "property_type" is translated_select and in input setting I select mm_property_type (MM no. 2.).

Now the problem is when I want to select in MM no. 1 in real estate form the property type, it's always empty. No data is showen, pulled from MM no.2.

What could be the problem?

Contao 3.2.14
MetaModels don't know the version.

**Comment by xantippe** [comment]
@EDsolution pls test it with the actual version of MM

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@EDsolution could you please have a final look at this and tell if your issue has been resolved?
