### ISSUE TITLE
[Frage] requires Contao < 3.4, ist das einzige, was ein Update unter Contao 3.4 verhindert

### ISSUE THREAD

**Issue by Znrl** [MetaModels/attribute_translatedselect#13]
Ich hatte mich nur darauf gefreut mit Contao 3.4.3 Metamodels wieder ohne irgendwelche Änderungen per Composer updaten zu können (bundle_all) translated_select ist meine ich das einzige, das das verhindert.
Deshalb die Frage, ob das angepasst werden kann oder obs da nen Grund gibt.

**Comment by discordier** [comment]
Kann es. Der Grund ist: hat halt noch keiner gemacht. ;)

**Comment by discordier** [comment]
Fixed in 0fa05bea3630e4e4491a936fb495abdc08bc8642
