### ISSUE TITLE
Attempted to call an undefined method named "getDatabase" of class "MetaModels\AttributeTranslatedSelectBundle\Attribute\TranslatedSelect".

### ISSUE THREAD

**Issue by pliou** [MetaModels/attribute_translatedselect#23]
Ich glaube attribute_select hat diesen Aufruf auf $this->connection umgeändert?

**Comment by DenizGelion** [comment]
Gibt es hierfür einen temporären workaround?

**Comment by zonky2** [comment]
@pliou bitte kompletten Stacktrace posten...

**Comment by pliou** [comment]
![trans_sele](https://user-images.githubusercontent.com/45556500/55937499-64782f00-5c39-11e9-813a-de26d2ff85a6.png)

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@pliou could you please have a final look at this and tell if your issue has been resolved?

**Comment by stefanheimes** [comment]
Fix is in the new version 2.1.2, please test and let us know if it is better now.

**Comment by zonky2** [comment]
it´s tested...
