### ISSUE TITLE
"Untranslated table for sorting" steht im Template nicht zur verfügung

### ISSUE THREAD

**Issue by paulpflug** [MetaModels/attribute_translatedselect#5]
Die zusätzlich angebare Tabelle funktioniert zum sortieren, steht aber im Template nicht zu Verfügung.

**Comment by xantippe** [comment]
@paulpflug bitte testen, ob noch aktuell

**Comment by paulpflug** [comment]
Bin mir da nicht mehr sicher, könnte aber sein, dass das mit #7 erledigt war?
Kann das auch gerade nicht testen, bin aber zuversichtlich, dass es behoben wurde :smile:.
