### ISSUE TITLE
Filter "Einfache Abfrage" löst auto_item nicht korrekt auf wenn das Alias Bindestriche enthält.

### ISSUE THREAD

**Issue by Teetrinker** [MetaModels/attribute_translatedselect#9]
Ich habe ein Metamodel (Projekt),
	dieses enthält ein Attribut "Translatedselect" - das auf die Namen eines zweiten MMs verweist (Kategorie).

Ich habe einen Filter vom Typ "Einfache Abfrage".
Dieser verwendet das Attribut Kategorie (translatedselect) und auto_item.
Wenn der Name der Kategorie keine Leerschläge enthält wird der Zusammenhang Alias/Kategorie/Name der Kategorie korrekt hergestellt.

Der Name einer Kategorie enthält Leerschläge ("Point of Sale").
Das gebildete Alias lautet "point-of-sale".
Der Filter löst das Alias nicht korrekt auf.

Bsp:

/kategorie/events
-> Es werden alle Projekte mit der Kategorie "Events" angezeigt

/kategorie/point-of-sale
-> Es werden keine Projekte ausgegeben, auch keine Errormeldung.

Das Problem tritt nur bei translatedselect's auf - nicht bei normalen Select's.

Verwendet wurde Mm-nightly-build vom 23.08.2014

**Comment by xantippe** [comment]
@Teetrinker  bitte prüfen, ob noch aktuell

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Teetrinker could you please have a final look at this and tell if your issue has been resolved?

**Comment by Teetrinker** [comment]
Habe derzeit leider nicht die Möglichkeit um das zu testen.
